import RealtimePicker

channellist = []
for i in ['ACB','AIGLE','BALST','BAULM','BERGE','BERNI','BNALP','BOURR','BRANT', 'CHAMB','CHASS','COLLE','DAGMA','DAVOX','DIX','EMBD', 'EMING', 'FIESA','FUORN','FUSIO','GIMEL','GOURZ','GRIMS','HAUIG','ILLEZ','JAUN','LADOL','LASAR','LAUCH','LIENZ','LKBD2', 'LLS','METMA','MESRY','MFERR','MMK','MTI02','MUGIO','MUO','PANIX','PERON','PLONS','ROTHE', 'SAIRA','SALAN','SALEV','SAVIG','SENIN','SIMPL','SLE','SULZ','TORNY','TRULL','VANNI','VDL','VDR','VINZL','VMV','WALHA','WEIN2','WGT','WILA','WIMIS','ZUR']:
    for channel in 'Z','N','E':
        channellist.append(f"CH.{i}..HH{channel}")
for i in ['ACB','AIGLE','BALST','BERNI','BLOTZ','BNALP','BOBI','BOURR','BRANT','BULAC','CHALL','CHAMB','CHASS','DAVOX','DIX','EWZT0','FIESA','FUORN','FUSIO','GIMEL','GRIMS','GRYON','HAMIK','HASLI','HAUIG','JAUN','LADOL','LIENZ','LKBD2','LLS','MFERR','MMK','MTI03','MUGIO','MUO','OTTER','PANIX','PLONS','ROMAN','SAARA','SAIG','SALAN','SAPK','SARD','SARE','SARK','SAUR','SAYF2','SAXE','SAXE','SAXE','SBAF','SBAJ2','SBAK','SBAM2','SBAP','SBAS','SBAT2','SBAV','SBAW','SBEF','SBERN','SBGN','SBIF2','SBIK','SBIS2','SBRE','SBUB','SBUH','SBUL','SBUS','SBUS','SCAS2','SCEL','SCHAT','SCHIO','SCHK','SCHS','SCME','SCOD','SCOU','SCRM','SCUG','SDAK','SDES','SENGL','SENIN','SEFS','SEMOS','SEPFL','SFEL','SFRA','SFRS','SFRU','SGAK','SGEV','SGLK','SGWS','SHER','SHEK','SIEB','SIMPL','SINS','SIOH','SIOM','SIOO','SIOV','SIZS','SKEK','SKIES','SKLW','SKRK','SLE','SLENK','SLIES','SLOP','SLTM2','SLUB','SLUK','SLUW','SLUX','SMAO','SMELS','SMFL','SMOE','SNES2','SNIB','SNTZ','SOLB','SOLZ','SONUG','SRENH','SRER','SRFW','SRHB','SRHE','SRHH','SSCN','SSMS','SSTS','STAF','STHK','STIEG','STRW','STSP','STSW2','SULZ','SUSI','SVAM','SVBE','SVEJ','SVIK','SVIL','SVIO','SVIS1','SVIT','SWAS','SWERG','SWIK','SWIM','SYVP','SZEK','SZIM','SZUZ','TORNY','TRULL','VDL','VDR','VINZL','VMV','WEIN2','WGT','WILA','WIMIS','WOLEN','ZUR']:
    for channel in 'Z','N','E':
        channellist.append(f"CH.{i}..HG{channel}")


print(channellist)
channellist = channellist[0:60]
r = RealtimePicker.RealtimePicker('seedlink.ethz.ch:18000',channellist)
print("Complete")
#['CH.BALST..HHZ','CH.ZUR..HHZ','CH.MMK..HHZ', 'CH.BALST..HHN','CH.ZUR..HHN','CH.MMK..HHN', 'CH.BALST..HHE','CH.ZUR..HHE','CH.MMK..HHE'])
